events {}

http {
    upstream app_server {
        server app:3000;
    }

    server {
        listen 80;

        # 큰 JSON/Base64 요청 허용
        client_max_body_size 10M;

        location / {
            proxy_pass http://app_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}